import { MovieDetailRes, MovieListRes } from "../src/interface";

export const movieListResMock: MovieListRes = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg",
      genre_ids: [28, 12, 878],
      id: 76341,
      original_language: "en",
      original_title: "Mad Max: Fury Road",
      overview:
        "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
      popularity: 585.849,
      poster_path: "/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
      release_date: "2015-05-13",
      title: "Mad Max: Fury Road",
      video: false,
      vote_average: 7.595,
      vote_count: 21773,
    },
    {
      adult: false,
      backdrop_path: "/4TFCA5Lm5miseV3Wy02yxurEQL9.jpg",
      genre_ids: [878, 28, 18, 53],
      id: 119450,
      original_language: "en",
      original_title: "Dawn of the Planet of the Apes",
      overview:
        "A group of scientists in San Francisco struggle to stay alive in the aftermath of a plague that is wiping out humanity, while Caesar tries to maintain dominance over his community of intelligent apes.",
      popularity: 558.124,
      poster_path: null,
      release_date: "2014-07-08",
      title: "Dawn of the Planet of the Apes",
      video: false,
      vote_average: 7.32,
      vote_count: 10951,
    },
    {
      adult: false,
      backdrop_path: "",
      genre_ids: [28, 12, 53, 80],
      id: 7451,
      original_language: "en",
      original_title: "xXx",
      overview:
        'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
      popularity: 458.434,
      poster_path: "",
      release_date: "2002-08-09",
      title: "xXx",
      video: false,
      vote_average: 5.933,
      vote_count: 4066,
    },
  ],
  total_pages: 27401,
  total_results: 548017,
  isLoading: false,
  isError: false,
};

export const movieDetailMock: MovieDetailRes = {
  adult: false,
  backdrop_path: "/c1Ywtvlqls6tPBZ3BqbPtBwHyng.jpg",
  belongs_to_collection: {
    id: 427084,
    name: "The Secret Life of Pets Collection",
    poster_path: "/d83LVydlQonKdshwQyLYx48D3LH.jpg",
    backdrop_path: "/fAibj0DIT8gk5jQtsEor66QKCsR.jpg",
  },
  budget: 75000000,
  genres: [
    { id: 12, name: "Adventure" },
    { id: 35, name: "Comedy" },
    { id: 16, name: "Animation" },
    { id: 10751, name: "Family" },
  ],
  homepage: "http://www.thesecretlifeofpets.com/",
  id: 328111,
  imdb_id: "tt2709768",
  origin_country: ["US"],
  original_language: "en",
  original_title: "The Secret Life of Pets",
  overview:
    "The quiet life of a terrier named Max is upended when his owner takes in Duke, a stray whom Max instantly dislikes.",
  popularity: 18.294,
  poster_path: "/g3Hms6AE174doeGR1gz5zX5sVsv.jpg",
  production_companies: [
    {
      id: 6704,
      logo_path: "/fOG2oY4m1YuYTQh4bMqqZkmgOAI.png",
      name: "Illumination",
      origin_country: "US",
    },
    {
      id: 33,
      logo_path: "/8lvHyhjr8oUKOOy2dKXoALWKdp0.png",
      name: "Universal Pictures",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2016-06-18",
  revenue: 875457937,
  runtime: 86,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "Think this is what they do all day?",
  title: "The Secret Life of Pets",
  video: false,
  vote_average: 6.275,
  vote_count: 7869,
};
